const PDFDocument = require('pdfkit');
const { Parser } = require('json2csv');
const db = require('../config/db');

class ExportService {
    /**
     * Generate Prescription PDF
     */
    async generatePrescriptionPDF(appointmentId, res) {
        const query = `
            SELECT a.*, p.first_name as patient_first, p.last_name as patient_last, p.dob,
                   d.first_name as doctor_first, d.last_name as doctor_last, d.specialty
            FROM appointments a
            JOIN patients p ON a.patient_id = p.id
            JOIN doctors d ON a.doctor_id = d.id
            WHERE a.id = ?
        `;
        const [[appt]] = await db.query(query, [appointmentId]);

        if (!appt) throw new Error('Appointment not found');

        const doc = new PDFDocument();
        doc.pipe(res);

        // Header
        doc.fontSize(20).text('Medical Prescription', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Date: ${new Date(appt.appointment_date).toLocaleDateString()}`);
        doc.text(`Appointment ID: ${appt.id}`);
        doc.moveDown();

        // Doctor Info
        doc.fontSize(14).text(`Doctor: Dr. ${appt.doctor_first} ${appt.doctor_last}`, { underline: true });
        doc.fontSize(12).text(`Specialty: ${appt.specialty}`);
        doc.moveDown();

        // Patient Info
        doc.fontSize(14).text(`Patient: ${appt.patient_first} ${appt.patient_last}`, { underline: true });
        doc.fontSize(12).text(`DOB: ${new Date(appt.dob).toLocaleDateString()}`);
        doc.moveDown();

        // Prescription
        doc.fontSize(14).text('Prescription:', { underline: true });
        doc.fontSize(12).text(appt.prescription || 'No prescription recorded.');
        doc.moveDown();

        // Diagnosis/Notes
        if (appt.diagnosis) {
            doc.fontSize(14).text('Diagnosis:', { underline: true });
            doc.fontSize(12).text(appt.diagnosis);
            doc.moveDown();
        }

        // Footer
        doc.fontSize(10).text('Generated by Hospital Management System', { align: 'center', bottom: 20 });

        doc.end();
    }

    /**
     * Export Vitals CSV
     */
    async exportVitalsCSV(patientId, res) {
        const query = `
            SELECT v.*, a.appointment_date
            FROM vitals v
            JOIN appointments a ON v.appointment_id = a.id
            WHERE a.patient_id = ?
            ORDER BY a.appointment_date DESC
        `;
        const [vitals] = await db.query(query, [patientId]);

        const fields = ['appointment_date', 'blood_pressure', 'heart_rate', 'temperature', 'oxygen_saturation', 'weight'];
        const json2csvParser = new Parser({ fields });
        const csv = json2csvParser.parse(vitals);

        res.header('Content-Type', 'text/csv');
        res.attachment(`vitals_history_${patientId}.csv`);
        res.send(csv);
    }
}

module.exports = new ExportService();
